root: true
extends:
  - standard
  - plugin:markdown/recommended
  - plugin:prettier/recommended
plugins:
  - markdown
overrides:
  - files: '**/*.md'
    processor: 'markdown/markdown'
rules:
  no-param-reassign: error
